name: Publish to NPM

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Node.js for npm publish
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: bun install

      - name: Build package
        run: bun run build

      - name: Run tests
        run: bun run test:run

      - name: Debug info
        run: |
          echo "Git ref: ${{ github.ref }}"
          echo "Git ref type: ${{ github.ref_type }}"
          echo "Is tag: ${{ startsWith(github.ref, 'refs/tags/') }}"
          echo "Is main branch: ${{ github.ref == 'refs/heads/main' }}"

      - name: Publish to NPM (tagged release)
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/')

      - name: Publish to NPM (main branch)
        run: npm publish --tag beta --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: github.ref == 'refs/heads/main'
